name: Bug Report
description: Report a Bug
labels:
  - bug
assignees:
  - Max094Reikeb
body:
  - type: textarea
    id: bug_desc
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
          1. Do '...'
          2. Use '...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Mod Informations
  - type: dropdown
    id: mod_ver
    attributes:
      label: |
        Mod Version
      options:
        - "1.5.3"
    validations:
      required: true
  - type: dropdown
    id: mc_ver
    attributes:
      label: |
        Minecraft Version
      options:
        - "1.20.1"
    validations:
      required: true
  - type: dropdown
    id: fb_loader_ver
    attributes:
      label: |
        Fabric Loader Version
      options:
        - "0.14.21"
    validations:
      required: true
  - type: dropdown
    id: fb_api_ver
    attributes:
      label: |
        Fabric API Version
      options:
        - "0.85.0"
    validations:
      required: true
  - type: textarea
    id: additional_ctx
    attributes:
      label: Additional Context
      placeholder: Add any other context about the problem here.
    validations:
      required: false